# Generated by Django 4.1.3 on 2022-11-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_profile_email_alter_profile_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
