# Generated by Django 4.1.3 on 2022-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=30)),
                ('ModelName', models.CharField(max_length=30)),
                ('CarNumber', models.CharField(max_length=30)),
                ('Features', models.TextField()),
                ('IsAvailable', models.CharField(max_length=3)),
                ('CarImage', models.ImageField(default='navimg.jpeg', upload_to='profile_pics')),
                ('CostPerDay', models.IntegerField(default=5000)),
            ],
        ),
        migrations.CreateModel(
            name='otherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('from_data', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
    ]
