# Generated by Django 4.1.3 on 2022-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='CarImage',
            field=models.ImageField(default='navimg.jpeg', upload_to='cars_pics'),
        ),
    ]
