# Generated by Django 4.1.3 on 2022-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_alter_cars_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='carInsurance',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuelConsumption',
            field=models.CharField(default='20kmph', max_length=10),
        ),
    ]
