# Generated by Django 4.1.3 on 2022-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_cars_carinsurance_cars_fuelconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='CostPerDay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='carInsurance',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuelConsumption',
            field=models.CharField(max_length=10),
        ),
    ]
