# Generated by Django 4.1.3 on 2022-11-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_password'),
        ('Cars', '0005_alter_cars_costperday_alter_cars_carinsurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdetails',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='otherdetails',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='phone_number',
            field=models.ForeignKey(default='938155447', on_delete=django.db.models.deletion.CASCADE, related_name='carbookphonenumber', to='Users.profile'),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbookperson', to='Users.profile'),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carbookaddress', to='Users.profile'),
        ),
    ]
