# Generated by Django 4.1.3 on 2022-11-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_password'),
        ('Cars', '0006_remove_otherdetails_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='phone_number',
            field=models.ForeignKey(default='9038155447', on_delete=django.db.models.deletion.CASCADE, related_name='carbookphonenumber', to='Users.profile'),
        ),
    ]
