# Generated by Django 4.1.3 on 2022-11-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_password'),
        ('Cars', '0007_alter_otherdetails_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='address',
            field=models.ForeignKey(default='1-8-54/c', on_delete=django.db.models.deletion.CASCADE, related_name='carbookaddress', to='Users.profile'),
        ),
    ]
