# Generated by Django 4.1.3 on 2022-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0008_alter_otherdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='otherdetails',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
