# Generated by Django 4.1.3 on 2022-11-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_password'),
        ('Cars', '0010_delete_otherdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('from_data', models.DateField()),
                ('to_date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbookperson', to='Users.profile')),
            ],
        ),
    ]
