# Generated by Django 4.1.3 on 2022-11-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0011_otherdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
