# Generated by Django 4.1.3 on 2022-11-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0012_alter_otherdetails_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
