# Generated by Django 4.1.3 on 2022-11-30 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_profile_password'),
        ('Cars', '0013_delete_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarName', models.CharField(max_length=30)),
                ('ModelName', models.CharField(max_length=30)),
                ('CarNumber', models.CharField(max_length=30)),
                ('Features', models.TextField()),
                ('IsAvailable', models.CharField(max_length=3)),
                ('CarImage', models.ImageField(default='navimg.jpeg', upload_to='car_pics')),
                ('fuelConsumption', models.CharField(max_length=10)),
                ('carInsurance', models.CharField(max_length=3)),
                ('CostPerDay', models.IntegerField()),
                ('dealerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealername', to='Users.profile')),
            ],
        ),
    ]
