# Generated by Django 4.1.3 on 2022-11-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0014_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdetails',
            old_name='from_data',
            new_name='from_date',
        ),
    ]
