# Generated by Django 4.1.3 on 2022-11-30 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0015_rename_from_data_otherdetails_from_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 30, 12, 14, 13, 802124)),
        ),
    ]
