# Generated by Django 4.1.3 on 2022-11-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0016_alter_otherdetails_from_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetails',
            name='from_date',
            field=models.DateField(),
        ),
    ]
